# Generated by Django 5.2.4 on 2026-07-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_staff'], name='user_active_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'date_joined'], name='user_role_joined_idx'),
        ),
    ]
