# Generated by Django 5.2.4 on 2026-07-19 08:10

from django.db import migrations, models


def preserve_verified_payment_status(apps, schema_editor):
    Payment = apps.get_model('store', 'Payment')
    Payment.objects.filter(is_successful=True).update(status='Successful')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.RunPython(preserve_verified_payment_status, migrations.RunPython.noop),
    ]
