# Generated by Django 5.2.4 on 2026-07-20 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_enforce_database_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'is_paid', 'created_at'], name='order_status_paid_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_price'], name='order_total_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'price'], name='prod_cat_active_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='prod_created_at_idx'),
        ),
    ]
